### ISSUE TITLE
Update repo settings to delete branch on merge

### ISSUE THREAD

**Issue by slifty** [qco/bookliberator#11]
@kfogel could we [modify the repository settings](https://help.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches) to automatically delete branches when they are merged in?  Note: nothing is lost, it is possible to manually un-delete the branch on github.

Our branch flow means that 99% of the time non-automatic deletion will just mean an extra manual deletion step after merging a PR.

**Comment by kfogel** [comment]
+1 and done, @slifty.

**Comment by kfogel** [comment]
Closing this issue.
