### ISSUE TITLE
Populate contributing documentation

### ISSUE THREAD

**Issue by slifty** [qco/bookliberator#7]
CONTRIBUTING.md, CODE_OF_CONDUCT.md, and other related documentation should be put into the repository.

**Comment by kfogel** [comment]
I'll pick a CoC.  CONTRIBUTING.md usually needs to be customized pretty heavily for the project, but I can stub one out right now -- please feel free to edit it to the point of unrecognizeability.

**Comment by kfogel** [comment]
Done; closing this ticket.  We will continue to expand and improve on this documentation throughout the life of the project, of course.
